import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

export const configPath = fileURLToPath(new URL('../../redirects.json', import.meta.url));

export function loadConfig(path = configPath) {
  const config = JSON.parse(readFileSync(path, 'utf8'));
  const seen = new Set();
  for (const r of config.redirects) {
    for (const key of ['from', 'to']) {
      if (!r[key].startsWith('/') || !r[key].endsWith('/')) {
        throw new Error(`redirects.json: "${r[key]}" must start and end with "/"`);
      }
    }
    if (seen.has(r.from)) throw new Error(`redirects.json: duplicate "from" ${r.from}`);
    seen.add(r.from);
  }
  return config;
}

// Where an old path lands on the new site, before any fragment.
// An entry whose target page does not exist yet falls back to config.pendingFallback.
export function onSitePath(entry, config) {
  return entry.live ? entry.to : config.pendingFallback;
}

export function onSiteUrl(entry, config) {
  const path = onSitePath(entry, config);
  const fragment = entry.live && entry.fragment ? `#${entry.fragment}` : '';
  return `${config.site}${path}${fragment}`;
}

// interim: same path on the new site (relies on the site's own redirects).
// final: straight to the destination; every entry must be live.
export function stubTarget(entry, config, mode) {
  if (mode === 'interim') return `${config.site}${entry.from}`;
  if (mode === 'final') {
    if (!entry.live) throw new Error(`Cannot build a final stub: ${entry.from} is not live yet`);
    return onSiteUrl(entry, config);
  }
  throw new Error(`Unknown mode "${mode}" (use interim or final)`);
}

const esc = (s) => s.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;');

export function renderRedirect(target) {
  const canonical = target.split('#')[0];
  const url = esc(target);
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Redirecting…</title>
<link rel="canonical" href="${esc(canonical)}">
<meta http-equiv="refresh" content="0; url=${url}">
<script>location.replace(${JSON.stringify(target).replace(/</g, '\\u003c')});</script>
</head>
<body>
<p>This page has moved to <a href="${url}">${url}</a>.</p>
</body>
</html>
`;
}

export function renderNotFound(config, mode) {
  const map = Object.fromEntries(config.redirects.map((r) => [r.from, stubTarget(r, config, mode)]));
  const json = JSON.stringify(map).replace(/</g, '\\u003c');
  const home = JSON.stringify(`${config.site}/`);
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Page moved</title>
<meta name="robots" content="noindex">
<script>
(function () {
  var map = ${json};
  var path = location.pathname;
  if (path.charAt(path.length - 1) !== '/') path += '/';
  location.replace(map[path] || ${home});
})();
</script>
</head>
<body>
<p>This site has moved to <a href=${home}>${config.site}</a>.</p>
</body>
</html>
`;
}

export function buildStub(config, mode) {
  const files = new Map();
  for (const r of config.redirects) {
    files.set(`${r.from.slice(1)}index.html`, renderRedirect(stubTarget(r, config, mode)));
  }
  files.set('404.html', renderNotFound(config, mode));
  files.set('.nojekyll', '');
  files.set(
    'README.md',
    `# ${new URL(config.legacyHost).hostname}\n\nRedirect stub. Every old URL forwards to ${config.site}.\nGenerated by \`scripts/build-redirect-stub.mjs\` in the ${new URL(config.site).hostname} repo; do not edit by hand.\n`,
  );
  return files;
}
